### PR TITLE
Added:

### PR DESCRIPTION
**Pull request by Ne-k**
- Auto changing status -- Removed the website link from status and I didn't feel like making another case. 
- Console ui colors just because (`npm i colors`)

This *should* work, tested it partially. Sidenote, Github is a bitch and wouldn't let me create a PR from my fork.

### CODE REVIEW

**Review by CatusKing — CHANGES_REQUESTED** [review]
idk abt the colors

**Comment by CatusKing** [comment]
@Killerjet101 ?

**Comment by Killerjet101** [comment]
oops, ignore that lol. I was pushing buttons I did not know what it does XD

**Review by CatusKing — CHANGES_REQUESTED** [review]
no colors

**Comment by Ne-k** [comment]
For some reason I'm unable to edit the changed files in the pr.

**Comment by CatusKing** [comment]
you need to make a new pr with the new changes that would remove the color

**Comment by CatusKing** [comment]
correct a new commit

**Comment by HAHALOSAH** [comment]
No colors, don't see a point in using them

**Comment by CatusKing** [comment]
inactive pull request

**Pull request closed without merging**
